connect system/manager as sysdba

DROP USER test CASCADE;
CREATE USER test IDENTIFIED BY test;
GRANT DBA TO test;

connect test/test;

SET SERVEROUTPUT ON;

--IDEAS

--TENER UN TYPE UBICACION CON CALLE Y AVENIDA

CREATE OR REPLACE TYPE GPS AS OBJECT(
	LATITUD NUMBER, --NUMBER SOPORTA 38 DIGITOS
	LONGITUD NUMBER
)
/

CREATE OR REPLACE TYPE UBICACION AS OBJECT (
    CALLE   INTEGER,    -- CALLE EN LA QUE SE ENCUENTRA
    AV 	    INTEGER,    -- LA AVENIDA
	POS 	GPS	
)
/

--TENER EL TYPE HIDRANTE COMO EN EL CUADERNO

CREATE TYPE TOMAS AS varray(4) OF INTEGER; --Este es el array de las 4 tomas que tiene cada hidrante
/

CREATE OR REPLACE TYPE HIDRANTE AS OBJECT(
	LOCALIZACION UBICACION,
	TOMASHIDRANTE TOMAS,
	CAUDALESPERADO FLOAT,
	NUMERO INTEGER,
	TAMANOSALIDAS INTEGER,
	ESTADO INTEGER
)
/

CREATE TABLE HIDRANTES(H HIDRANTE); --La lista de hidrantes

--FUNCION CREAR SOLICITUD(QUE LE LLEGA AL DPTO ENCARGADO) INSTALACION O MANTENIMIENTO

--FUNCION REGISTRAR FORMULARIOS

--TENER UNA TABLA DE FORMULARIOS

--TENER UN TYPE BOMBERO QUE EJECUTA EL REGISTRAR FORMULARIO
CREATE OR REPLACE TYPE BOMBERO AS OBJECT(
	ID VARCHAR2(15),
	NOMBRE VARCHAR2(15),
	MEMBER PROCEDURE REGISTRARFORMULARIO
)
/

CREATE TABLE BOMBEROS(B BOMBERO); --La lista de bomberos


--TENER UN TYPE CAMION QUE EJECUTE EL METODO PRINCIPAL DEL PROYECTO
CREATE OR REPLACE TYPE CAMION AS OBJECT(
	ID VARCHAR2(15),
	MEMBER FUNCTION RPH(PUNTO_BUSQUEDA GPS,RADIO FLOAT) RETURN FLOAT
)
/

CREATE TABLE CAMIONES(C CAMION); --La lista de camiones

--PROCEDURES

--PROCEDURE PARA INSERTAR HIDRANTES

CREATE OR REPLACE PROCEDURE INSERTARHIDRANTES(XLOCAL UBICACION, XTOMAS TOMAS, XCAUDALESPERADO FLOAT, XNUMERO INTEGER, XTAMANOSALIDAS INTEGER, XESTADO INTEGER) IS
BEGIN
	INSERT INTO HIDRANTES VALUES(HIDRANTE(XLOCAL,XTOMAS,XCAUDALESPERADO,XNUMERO,XTAMANOSALIDAS,XESTADO));
	COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERTARHIDRANTES2(XCAUDALESPERADO FLOAT,XNUMERO INTEGER,XTAMANOSALIDAS INTEGER,XESTADO INTEGER) IS
	TOM TOMAS;
	UB UBICACION;
	GP GPS;
BEGIN
	TOM := TOMAS(1,5,6,7);
	GP := GPS(20.487,295.987);
	UB := UBICACION(10,14,GP);
	INSERT INTO HIDRANTES VALUES(HIDRANTE(UB,TOM,XCAUDALESPERADO,XNUMERO,XTAMANOSALIDAS,XESTADO));
	COMMIT;
END;
/

exec INSERTARHIDRANTES((9,10,(14.15987,-125.745)),(1,3,4,5),56.78,12,124,1);
exec INSERTARHIDRANTES2(56.78,12,124,1);--SIN TOMAS